/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ClusterNodeVMDeploymentRequest;
import io.swagger.client.model.ClusteringConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Contains a list of cluster node VM deployment requests and optionally a clustering configuration. 
 */
@Schema(description = "Contains a list of cluster node VM deployment requests and optionally a clustering configuration. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class AddClusterNodeVMInfo {
  @SerializedName("deployment_requests")
  private List<ClusterNodeVMDeploymentRequest> deploymentRequests = new ArrayList<ClusterNodeVMDeploymentRequest>();

  @SerializedName("clustering_config")
  private ClusteringConfig clusteringConfig = null;

  public AddClusterNodeVMInfo deploymentRequests(List<ClusterNodeVMDeploymentRequest> deploymentRequests) {
    this.deploymentRequests = deploymentRequests;
    return this;
  }

  public AddClusterNodeVMInfo addDeploymentRequestsItem(ClusterNodeVMDeploymentRequest deploymentRequestsItem) {
    this.deploymentRequests.add(deploymentRequestsItem);
    return this;
  }

   /**
   * Cluster node VM deployment requests to be deployed by the Manager. 
   * @return deploymentRequests
  **/
  @Schema(required = true, description = "Cluster node VM deployment requests to be deployed by the Manager. ")
  public List<ClusterNodeVMDeploymentRequest> getDeploymentRequests() {
    return deploymentRequests;
  }

  public void setDeploymentRequests(List<ClusterNodeVMDeploymentRequest> deploymentRequests) {
    this.deploymentRequests = deploymentRequests;
  }

  public AddClusterNodeVMInfo clusteringConfig(ClusteringConfig clusteringConfig) {
    this.clusteringConfig = clusteringConfig;
    return this;
  }

   /**
   * Get clusteringConfig
   * @return clusteringConfig
  **/
  @Schema(description = "")
  public ClusteringConfig getClusteringConfig() {
    return clusteringConfig;
  }

  public void setClusteringConfig(ClusteringConfig clusteringConfig) {
    this.clusteringConfig = clusteringConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddClusterNodeVMInfo addClusterNodeVMInfo = (AddClusterNodeVMInfo) o;
    return Objects.equals(this.deploymentRequests, addClusterNodeVMInfo.deploymentRequests) &&
        Objects.equals(this.clusteringConfig, addClusterNodeVMInfo.clusteringConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deploymentRequests, clusteringConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddClusterNodeVMInfo {\n");
    
    sb.append("    deploymentRequests: ").append(toIndentedString(deploymentRequests)).append("\n");
    sb.append("    clusteringConfig: ").append(toIndentedString(clusteringConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
