/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.RelatedApiError;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Detailed information about an API Error
 */
@Schema(description = "Detailed information about an API Error")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class ApiError extends RelatedApiError {
  @SerializedName("related_errors")
  private List<RelatedApiError> relatedErrors = null;

  public ApiError relatedErrors(List<RelatedApiError> relatedErrors) {
    this.relatedErrors = relatedErrors;
    return this;
  }

  public ApiError addRelatedErrorsItem(RelatedApiError relatedErrorsItem) {
    if (this.relatedErrors == null) {
      this.relatedErrors = new ArrayList<RelatedApiError>();
    }
    this.relatedErrors.add(relatedErrorsItem);
    return this;
  }

   /**
   * Other errors related to this error
   * @return relatedErrors
  **/
  @Schema(description = "Other errors related to this error")
  public List<RelatedApiError> getRelatedErrors() {
    return relatedErrors;
  }

  public void setRelatedErrors(List<RelatedApiError> relatedErrors) {
    this.relatedErrors = relatedErrors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiError apiError = (ApiError) o;
    return Objects.equals(this.relatedErrors, apiError.relatedErrors) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relatedErrors, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiError {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    relatedErrors: ").append(toIndentedString(relatedErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
