/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AppDiscoveryAppProfileResultSummary;
import io.swagger.client.model.AppDiscoverySession;
import io.swagger.client.model.AppProfileMetaInfo;
import io.swagger.client.model.NSGroupMetaInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Contains the summary of the results of an application discovery session 
 */
@Schema(description = "Contains the summary of the results of an application discovery session ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class AppDiscoverySessionResultSummary extends AppDiscoverySession {
  @SerializedName("app_profile_summary_list")
  private List<AppDiscoveryAppProfileResultSummary> appProfileSummaryList = null;

  @SerializedName("ns_groups")
  private List<NSGroupMetaInfo> nsGroups = null;

  @SerializedName("app_profiles")
  private List<AppProfileMetaInfo> appProfiles = null;

  public AppDiscoverySessionResultSummary appProfileSummaryList(List<AppDiscoveryAppProfileResultSummary> appProfileSummaryList) {
    this.appProfileSummaryList = appProfileSummaryList;
    return this;
  }

  public AppDiscoverySessionResultSummary addAppProfileSummaryListItem(AppDiscoveryAppProfileResultSummary appProfileSummaryListItem) {
    if (this.appProfileSummaryList == null) {
      this.appProfileSummaryList = new ArrayList<AppDiscoveryAppProfileResultSummary>();
    }
    this.appProfileSummaryList.add(appProfileSummaryListItem);
    return this;
  }

   /**
   * List of App Profiles summary discovered in this session
   * @return appProfileSummaryList
  **/
  @Schema(description = "List of App Profiles summary discovered in this session")
  public List<AppDiscoveryAppProfileResultSummary> getAppProfileSummaryList() {
    return appProfileSummaryList;
  }

  public void setAppProfileSummaryList(List<AppDiscoveryAppProfileResultSummary> appProfileSummaryList) {
    this.appProfileSummaryList = appProfileSummaryList;
  }

  public AppDiscoverySessionResultSummary nsGroups(List<NSGroupMetaInfo> nsGroups) {
    this.nsGroups = nsGroups;
    return this;
  }

  public AppDiscoverySessionResultSummary addNsGroupsItem(NSGroupMetaInfo nsGroupsItem) {
    if (this.nsGroups == null) {
      this.nsGroups = new ArrayList<NSGroupMetaInfo>();
    }
    this.nsGroups.add(nsGroupsItem);
    return this;
  }

   /**
   * List of NSGroups provided for discovery for this session
   * @return nsGroups
  **/
  @Schema(description = "List of NSGroups provided for discovery for this session")
  public List<NSGroupMetaInfo> getNsGroups() {
    return nsGroups;
  }

  public void setNsGroups(List<NSGroupMetaInfo> nsGroups) {
    this.nsGroups = nsGroups;
  }

  public AppDiscoverySessionResultSummary appProfiles(List<AppProfileMetaInfo> appProfiles) {
    this.appProfiles = appProfiles;
    return this;
  }

  public AppDiscoverySessionResultSummary addAppProfilesItem(AppProfileMetaInfo appProfilesItem) {
    if (this.appProfiles == null) {
      this.appProfiles = new ArrayList<AppProfileMetaInfo>();
    }
    this.appProfiles.add(appProfilesItem);
    return this;
  }

   /**
   * List of app profiles targeted to be classified for this session
   * @return appProfiles
  **/
  @Schema(description = "List of app profiles targeted to be classified for this session")
  public List<AppProfileMetaInfo> getAppProfiles() {
    return appProfiles;
  }

  public void setAppProfiles(List<AppProfileMetaInfo> appProfiles) {
    this.appProfiles = appProfiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppDiscoverySessionResultSummary appDiscoverySessionResultSummary = (AppDiscoverySessionResultSummary) o;
    return Objects.equals(this.appProfileSummaryList, appDiscoverySessionResultSummary.appProfileSummaryList) &&
        Objects.equals(this.nsGroups, appDiscoverySessionResultSummary.nsGroups) &&
        Objects.equals(this.appProfiles, appDiscoverySessionResultSummary.appProfiles) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appProfileSummaryList, nsGroups, appProfiles, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppDiscoverySessionResultSummary {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    appProfileSummaryList: ").append(toIndentedString(appProfileSummaryList)).append("\n");
    sb.append("    nsGroups: ").append(toIndentedString(nsGroups)).append("\n");
    sb.append("    appProfiles: ").append(toIndentedString(appProfiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
