/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BFDStatusCount
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class BFDStatusCount {
  @SerializedName("bfd_admin_down_count")
  private Integer bfdAdminDownCount = null;

  @SerializedName("bfd_up_count")
  private Integer bfdUpCount = null;

  @SerializedName("bfd_down_count")
  private Integer bfdDownCount = null;

  @SerializedName("bfd_init_count")
  private Integer bfdInitCount = null;

  public BFDStatusCount bfdAdminDownCount(Integer bfdAdminDownCount) {
    this.bfdAdminDownCount = bfdAdminDownCount;
    return this;
  }

   /**
   * Number of tunnels in BFD admin down state
   * @return bfdAdminDownCount
  **/
  @Schema(description = "Number of tunnels in BFD admin down state")
  public Integer getBfdAdminDownCount() {
    return bfdAdminDownCount;
  }

  public void setBfdAdminDownCount(Integer bfdAdminDownCount) {
    this.bfdAdminDownCount = bfdAdminDownCount;
  }

  public BFDStatusCount bfdUpCount(Integer bfdUpCount) {
    this.bfdUpCount = bfdUpCount;
    return this;
  }

   /**
   * Number of tunnels in BFD up state
   * @return bfdUpCount
  **/
  @Schema(description = "Number of tunnels in BFD up state")
  public Integer getBfdUpCount() {
    return bfdUpCount;
  }

  public void setBfdUpCount(Integer bfdUpCount) {
    this.bfdUpCount = bfdUpCount;
  }

  public BFDStatusCount bfdDownCount(Integer bfdDownCount) {
    this.bfdDownCount = bfdDownCount;
    return this;
  }

   /**
   * Number of tunnels in BFD down state
   * @return bfdDownCount
  **/
  @Schema(description = "Number of tunnels in BFD down state")
  public Integer getBfdDownCount() {
    return bfdDownCount;
  }

  public void setBfdDownCount(Integer bfdDownCount) {
    this.bfdDownCount = bfdDownCount;
  }

  public BFDStatusCount bfdInitCount(Integer bfdInitCount) {
    this.bfdInitCount = bfdInitCount;
    return this;
  }

   /**
   * Number of tunnels in BFD init state
   * @return bfdInitCount
  **/
  @Schema(description = "Number of tunnels in BFD init state")
  public Integer getBfdInitCount() {
    return bfdInitCount;
  }

  public void setBfdInitCount(Integer bfdInitCount) {
    this.bfdInitCount = bfdInitCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BFDStatusCount bfDStatusCount = (BFDStatusCount) o;
    return Objects.equals(this.bfdAdminDownCount, bfDStatusCount.bfdAdminDownCount) &&
        Objects.equals(this.bfdUpCount, bfDStatusCount.bfdUpCount) &&
        Objects.equals(this.bfdDownCount, bfDStatusCount.bfdDownCount) &&
        Objects.equals(this.bfdInitCount, bfDStatusCount.bfdInitCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bfdAdminDownCount, bfdUpCount, bfdDownCount, bfdInitCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BFDStatusCount {\n");
    
    sb.append("    bfdAdminDownCount: ").append(toIndentedString(bfdAdminDownCount)).append("\n");
    sb.append("    bfdUpCount: ").append(toIndentedString(bfdUpCount)).append("\n");
    sb.append("    bfdDownCount: ").append(toIndentedString(bfdDownCount)).append("\n");
    sb.append("    bfdInitCount: ").append(toIndentedString(bfdInitCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
