/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.EdgeClusterMemberAllocationPool;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EdgeClusterMemberAllocationProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class EdgeClusterMemberAllocationProfile {
  @SerializedName("allocation_pool")
  private EdgeClusterMemberAllocationPool allocationPool = null;

  @SerializedName("enable_standby_relocation")
  private Boolean enableStandbyRelocation = false;

  public EdgeClusterMemberAllocationProfile allocationPool(EdgeClusterMemberAllocationPool allocationPool) {
    this.allocationPool = allocationPool;
    return this;
  }

   /**
   * Get allocationPool
   * @return allocationPool
  **/
  @Schema(description = "")
  public EdgeClusterMemberAllocationPool getAllocationPool() {
    return allocationPool;
  }

  public void setAllocationPool(EdgeClusterMemberAllocationPool allocationPool) {
    this.allocationPool = allocationPool;
  }

  public EdgeClusterMemberAllocationProfile enableStandbyRelocation(Boolean enableStandbyRelocation) {
    this.enableStandbyRelocation = enableStandbyRelocation;
    return this;
  }

   /**
   * Flag to enable the auto-relocation of standby service router running on edge cluster and node associated with the logical router. Only dynamically allocated tier1 logical routers are considered for the relocation. 
   * @return enableStandbyRelocation
  **/
  @Schema(description = "Flag to enable the auto-relocation of standby service router running on edge cluster and node associated with the logical router. Only dynamically allocated tier1 logical routers are considered for the relocation. ")
  public Boolean isEnableStandbyRelocation() {
    return enableStandbyRelocation;
  }

  public void setEnableStandbyRelocation(Boolean enableStandbyRelocation) {
    this.enableStandbyRelocation = enableStandbyRelocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EdgeClusterMemberAllocationProfile edgeClusterMemberAllocationProfile = (EdgeClusterMemberAllocationProfile) o;
    return Objects.equals(this.allocationPool, edgeClusterMemberAllocationProfile.allocationPool) &&
        Objects.equals(this.enableStandbyRelocation, edgeClusterMemberAllocationProfile.enableStandbyRelocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allocationPool, enableStandbyRelocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EdgeClusterMemberAllocationProfile {\n");
    
    sb.append("    allocationPool: ").append(toIndentedString(allocationPool)).append("\n");
    sb.append("    enableStandbyRelocation: ").append(toIndentedString(enableStandbyRelocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
