/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GlobalConfigs;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NSX global configs for Distributed Firewall
 */
@Schema(description = "NSX global configs for Distributed Firewall")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class FirewallGlobalConfig extends GlobalConfigs {
  @SerializedName("global_fastpath_mode_enabled")
  private Boolean globalFastpathModeEnabled = true;

  @SerializedName("global_addrset_mode_enabled")
  private Boolean globalAddrsetModeEnabled = true;

  public FirewallGlobalConfig globalFastpathModeEnabled(Boolean globalFastpathModeEnabled) {
    this.globalFastpathModeEnabled = globalFastpathModeEnabled;
    return this;
  }

   /**
   * When this flag is set to true, fast path searching is enabled in Distributed Firewall.
   * @return globalFastpathModeEnabled
  **/
  @Schema(description = "When this flag is set to true, fast path searching is enabled in Distributed Firewall.")
  public Boolean isGlobalFastpathModeEnabled() {
    return globalFastpathModeEnabled;
  }

  public void setGlobalFastpathModeEnabled(Boolean globalFastpathModeEnabled) {
    this.globalFastpathModeEnabled = globalFastpathModeEnabled;
  }

  public FirewallGlobalConfig globalAddrsetModeEnabled(Boolean globalAddrsetModeEnabled) {
    this.globalAddrsetModeEnabled = globalAddrsetModeEnabled;
    return this;
  }

   /**
   * When this flag is set to true, global address set is enabled in Distributed Firewall.
   * @return globalAddrsetModeEnabled
  **/
  @Schema(description = "When this flag is set to true, global address set is enabled in Distributed Firewall.")
  public Boolean isGlobalAddrsetModeEnabled() {
    return globalAddrsetModeEnabled;
  }

  public void setGlobalAddrsetModeEnabled(Boolean globalAddrsetModeEnabled) {
    this.globalAddrsetModeEnabled = globalAddrsetModeEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FirewallGlobalConfig firewallGlobalConfig = (FirewallGlobalConfig) o;
    return Objects.equals(this.globalFastpathModeEnabled, firewallGlobalConfig.globalFastpathModeEnabled) &&
        Objects.equals(this.globalAddrsetModeEnabled, firewallGlobalConfig.globalAddrsetModeEnabled) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(globalFastpathModeEnabled, globalAddrsetModeEnabled, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FirewallGlobalConfig {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    globalFastpathModeEnabled: ").append(toIndentedString(globalFastpathModeEnabled)).append("\n");
    sb.append("    globalAddrsetModeEnabled: ").append(toIndentedString(globalAddrsetModeEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
