/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Label;
import io.swagger.client.model.PointDefinition;
import io.swagger.client.model.RenderConfiguration;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Defines a graph
 */
@Schema(description = "Defines a graph")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class GraphDefinition {
  @SerializedName("point_definition")
  private PointDefinition pointDefinition = null;

  @SerializedName("label")
  private Label label = null;

  @SerializedName("render_configuration")
  private List<RenderConfiguration> renderConfiguration = null;

  public GraphDefinition pointDefinition(PointDefinition pointDefinition) {
    this.pointDefinition = pointDefinition;
    return this;
  }

   /**
   * Get pointDefinition
   * @return pointDefinition
  **/
  @Schema(required = true, description = "")
  public PointDefinition getPointDefinition() {
    return pointDefinition;
  }

  public void setPointDefinition(PointDefinition pointDefinition) {
    this.pointDefinition = pointDefinition;
  }

  public GraphDefinition label(Label label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @Schema(description = "")
  public Label getLabel() {
    return label;
  }

  public void setLabel(Label label) {
    this.label = label;
  }

  public GraphDefinition renderConfiguration(List<RenderConfiguration> renderConfiguration) {
    this.renderConfiguration = renderConfiguration;
    return this;
  }

  public GraphDefinition addRenderConfigurationItem(RenderConfiguration renderConfigurationItem) {
    if (this.renderConfiguration == null) {
      this.renderConfiguration = new ArrayList<RenderConfiguration>();
    }
    this.renderConfiguration.add(renderConfigurationItem);
    return this;
  }

   /**
   * Additional rendering or conditional evaluation of the field values to be performed, if any.
   * @return renderConfiguration
  **/
  @Schema(description = "Additional rendering or conditional evaluation of the field values to be performed, if any.")
  public List<RenderConfiguration> getRenderConfiguration() {
    return renderConfiguration;
  }

  public void setRenderConfiguration(List<RenderConfiguration> renderConfiguration) {
    this.renderConfiguration = renderConfiguration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GraphDefinition graphDefinition = (GraphDefinition) o;
    return Objects.equals(this.pointDefinition, graphDefinition.pointDefinition) &&
        Objects.equals(this.label, graphDefinition.label) &&
        Objects.equals(this.renderConfiguration, graphDefinition.renderConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointDefinition, label, renderConfiguration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GraphDefinition {\n");
    
    sb.append("    pointDefinition: ").append(toIndentedString(pointDefinition)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    renderConfiguration: ").append(toIndentedString(renderConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
