/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.IPSecVPNTrafficCounters;
import io.swagger.client.model.ResourceReference;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IPSec VPN session traffic summary.
 */
@Schema(description = "IPSec VPN session traffic summary.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class IPSecVPNSessionTrafficSummary {
  @SerializedName("traffic_counters")
  private IPSecVPNTrafficCounters trafficCounters = null;

  @SerializedName("ipsec_vpn_session")
  private ResourceReference ipsecVpnSession = null;

  public IPSecVPNSessionTrafficSummary trafficCounters(IPSecVPNTrafficCounters trafficCounters) {
    this.trafficCounters = trafficCounters;
    return this;
  }

   /**
   * Get trafficCounters
   * @return trafficCounters
  **/
  @Schema(description = "")
  public IPSecVPNTrafficCounters getTrafficCounters() {
    return trafficCounters;
  }

  public void setTrafficCounters(IPSecVPNTrafficCounters trafficCounters) {
    this.trafficCounters = trafficCounters;
  }

  public IPSecVPNSessionTrafficSummary ipsecVpnSession(ResourceReference ipsecVpnSession) {
    this.ipsecVpnSession = ipsecVpnSession;
    return this;
  }

   /**
   * Get ipsecVpnSession
   * @return ipsecVpnSession
  **/
  @Schema(description = "")
  public ResourceReference getIpsecVpnSession() {
    return ipsecVpnSession;
  }

  public void setIpsecVpnSession(ResourceReference ipsecVpnSession) {
    this.ipsecVpnSession = ipsecVpnSession;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPSecVPNSessionTrafficSummary ipSecVPNSessionTrafficSummary = (IPSecVPNSessionTrafficSummary) o;
    return Objects.equals(this.trafficCounters, ipSecVPNSessionTrafficSummary.trafficCounters) &&
        Objects.equals(this.ipsecVpnSession, ipSecVPNSessionTrafficSummary.ipsecVpnSession);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trafficCounters, ipsecVpnSession);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPSecVPNSessionTrafficSummary {\n");
    
    sb.append("    trafficCounters: ").append(toIndentedString(trafficCounters)).append("\n");
    sb.append("    ipsecVpnSession: ").append(toIndentedString(ipsecVpnSession)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
