/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LbRuleCondition;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * This condition is used to match HTTP request messages by cookie which is a specific type of HTTP header. The match_type and case_sensitive define how to compare cookie value. 
 */
@Schema(description = "This condition is used to match HTTP request messages by cookie which is a specific type of HTTP header. The match_type and case_sensitive define how to compare cookie value. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class LbHttpRequestCookieCondition extends LbRuleCondition {
  /**
   * Match type of cookie value
   */
  @JsonAdapter(MatchTypeEnum.Adapter.class)
  public enum MatchTypeEnum {
    STARTS_WITH("STARTS_WITH"),
    ENDS_WITH("ENDS_WITH"),
    EQUALS("EQUALS"),
    CONTAINS("CONTAINS"),
    REGEX("REGEX");

    private String value;

    MatchTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static MatchTypeEnum fromValue(String text) {
      for (MatchTypeEnum b : MatchTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<MatchTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MatchTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MatchTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MatchTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("match_type")
  private MatchTypeEnum matchType = MatchTypeEnum.REGEX;

  @SerializedName("cookie_name")
  private String cookieName = null;

  @SerializedName("cookie_value")
  private String cookieValue = null;

  @SerializedName("case_sensitive")
  private Boolean caseSensitive = true;

  public LbHttpRequestCookieCondition matchType(MatchTypeEnum matchType) {
    this.matchType = matchType;
    return this;
  }

   /**
   * Match type of cookie value
   * @return matchType
  **/
  @Schema(description = "Match type of cookie value")
  public MatchTypeEnum getMatchType() {
    return matchType;
  }

  public void setMatchType(MatchTypeEnum matchType) {
    this.matchType = matchType;
  }

  public LbHttpRequestCookieCondition cookieName(String cookieName) {
    this.cookieName = cookieName;
    return this;
  }

   /**
   * Name of cookie
   * @return cookieName
  **/
  @Schema(required = true, description = "Name of cookie")
  public String getCookieName() {
    return cookieName;
  }

  public void setCookieName(String cookieName) {
    this.cookieName = cookieName;
  }

  public LbHttpRequestCookieCondition cookieValue(String cookieValue) {
    this.cookieValue = cookieValue;
    return this;
  }

   /**
   * Value of cookie
   * @return cookieValue
  **/
  @Schema(required = true, description = "Value of cookie")
  public String getCookieValue() {
    return cookieValue;
  }

  public void setCookieValue(String cookieValue) {
    this.cookieValue = cookieValue;
  }

  public LbHttpRequestCookieCondition caseSensitive(Boolean caseSensitive) {
    this.caseSensitive = caseSensitive;
    return this;
  }

   /**
   * If true, case is significant when comparing cookie value. 
   * @return caseSensitive
  **/
  @Schema(description = "If true, case is significant when comparing cookie value. ")
  public Boolean isCaseSensitive() {
    return caseSensitive;
  }

  public void setCaseSensitive(Boolean caseSensitive) {
    this.caseSensitive = caseSensitive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LbHttpRequestCookieCondition lbHttpRequestCookieCondition = (LbHttpRequestCookieCondition) o;
    return Objects.equals(this.matchType, lbHttpRequestCookieCondition.matchType) &&
        Objects.equals(this.cookieName, lbHttpRequestCookieCondition.cookieName) &&
        Objects.equals(this.cookieValue, lbHttpRequestCookieCondition.cookieValue) &&
        Objects.equals(this.caseSensitive, lbHttpRequestCookieCondition.caseSensitive) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchType, cookieName, cookieValue, caseSensitive, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LbHttpRequestCookieCondition {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    matchType: ").append(toIndentedString(matchType)).append("\n");
    sb.append("    cookieName: ").append(toIndentedString(cookieName)).append("\n");
    sb.append("    cookieValue: ").append(toIndentedString(cookieValue)).append("\n");
    sb.append("    caseSensitive: ").append(toIndentedString(caseSensitive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
