/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SSL protocol
 */
@Schema(description = "SSL protocol")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class LbSslProtocolInfo {
  @SerializedName("is_default")
  private Boolean isDefault = null;

  @SerializedName("is_secure")
  private Boolean isSecure = null;

  /**
   * SSL protocol
   */
  @JsonAdapter(ProtocolEnum.Adapter.class)
  public enum ProtocolEnum {
    SSL_V2("SSL_V2"),
    SSL_V3("SSL_V3"),
    TLS_V1("TLS_V1"),
    TLS_V1_1("TLS_V1_1"),
    TLS_V1_2("TLS_V1_2");

    private String value;

    ProtocolEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ProtocolEnum fromValue(String text) {
      for (ProtocolEnum b : ProtocolEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ProtocolEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProtocolEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProtocolEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ProtocolEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("protocol")
  private ProtocolEnum protocol = null;

  public LbSslProtocolInfo isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Default SSL protocol flag
   * @return isDefault
  **/
  @Schema(required = true, description = "Default SSL protocol flag")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public LbSslProtocolInfo isSecure(Boolean isSecure) {
    this.isSecure = isSecure;
    return this;
  }

   /**
   * Secure/insecure SSL protocol flag
   * @return isSecure
  **/
  @Schema(required = true, description = "Secure/insecure SSL protocol flag")
  public Boolean isIsSecure() {
    return isSecure;
  }

  public void setIsSecure(Boolean isSecure) {
    this.isSecure = isSecure;
  }

  public LbSslProtocolInfo protocol(ProtocolEnum protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * SSL protocol
   * @return protocol
  **/
  @Schema(required = true, description = "SSL protocol")
  public ProtocolEnum getProtocol() {
    return protocol;
  }

  public void setProtocol(ProtocolEnum protocol) {
    this.protocol = protocol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LbSslProtocolInfo lbSslProtocolInfo = (LbSslProtocolInfo) o;
    return Objects.equals(this.isDefault, lbSslProtocolInfo.isDefault) &&
        Objects.equals(this.isSecure, lbSslProtocolInfo.isSecure) &&
        Objects.equals(this.protocol, lbSslProtocolInfo.protocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isDefault, isSecure, protocol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LbSslProtocolInfo {\n");
    
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    isSecure: ").append(toIndentedString(isSecure)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
