/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Filter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * LogicalPortStatusSummary
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class LogicalPortStatusSummary {
  @SerializedName("total_ports")
  private Long totalPorts = null;

  @SerializedName("last_update_timestamp")
  private Long lastUpdateTimestamp = null;

  @SerializedName("up_ports")
  private Long upPorts = null;

  @SerializedName("filters")
  private List<Filter> filters = null;

  public LogicalPortStatusSummary totalPorts(Long totalPorts) {
    this.totalPorts = totalPorts;
    return this;
  }

   /**
   * The total number of logical ports.
   * @return totalPorts
  **/
  @Schema(required = true, description = "The total number of logical ports.")
  public Long getTotalPorts() {
    return totalPorts;
  }

  public void setTotalPorts(Long totalPorts) {
    this.totalPorts = totalPorts;
  }

   /**
   * Timestamp when the data was last updated; unset if data source has never updated the data.
   * @return lastUpdateTimestamp
  **/
  @Schema(description = "Timestamp when the data was last updated; unset if data source has never updated the data.")
  public Long getLastUpdateTimestamp() {
    return lastUpdateTimestamp;
  }

  public LogicalPortStatusSummary upPorts(Long upPorts) {
    this.upPorts = upPorts;
    return this;
  }

   /**
   * The number of logical ports whose Operational status is UP
   * @return upPorts
  **/
  @Schema(required = true, description = "The number of logical ports whose Operational status is UP")
  public Long getUpPorts() {
    return upPorts;
  }

  public void setUpPorts(Long upPorts) {
    this.upPorts = upPorts;
  }

  public LogicalPortStatusSummary filters(List<Filter> filters) {
    this.filters = filters;
    return this;
  }

  public LogicalPortStatusSummary addFiltersItem(Filter filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<Filter>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * The filters used to find the logical ports- TransportZone id, LogicalSwitch id or LogicalSwitchProfile id
   * @return filters
  **/
  @Schema(description = "The filters used to find the logical ports- TransportZone id, LogicalSwitch id or LogicalSwitchProfile id")
  public List<Filter> getFilters() {
    return filters;
  }

  public void setFilters(List<Filter> filters) {
    this.filters = filters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogicalPortStatusSummary logicalPortStatusSummary = (LogicalPortStatusSummary) o;
    return Objects.equals(this.totalPorts, logicalPortStatusSummary.totalPorts) &&
        Objects.equals(this.lastUpdateTimestamp, logicalPortStatusSummary.lastUpdateTimestamp) &&
        Objects.equals(this.upPorts, logicalPortStatusSummary.upPorts) &&
        Objects.equals(this.filters, logicalPortStatusSummary.filters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalPorts, lastUpdateTimestamp, upPorts, filters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogicalPortStatusSummary {\n");
    
    sb.append("    totalPorts: ").append(toIndentedString(totalPorts)).append("\n");
    sb.append("    lastUpdateTimestamp: ").append(toIndentedString(lastUpdateTimestamp)).append("\n");
    sb.append("    upPorts: ").append(toIndentedString(upPorts)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
