/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MigrationFeedbackResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * List of detailed feedback response for the migration tool.
 */
@Schema(description = "List of detailed feedback response for the migration tool.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class MigrationFeedbackResponseList {
  @SerializedName("response_list")
  private List<MigrationFeedbackResponse> responseList = new ArrayList<MigrationFeedbackResponse>();

  public MigrationFeedbackResponseList responseList(List<MigrationFeedbackResponse> responseList) {
    this.responseList = responseList;
    return this;
  }

  public MigrationFeedbackResponseList addResponseListItem(MigrationFeedbackResponse responseListItem) {
    this.responseList.add(responseListItem);
    return this;
  }

   /**
   * List of feedback responses.
   * @return responseList
  **/
  @Schema(required = true, description = "List of feedback responses.")
  public List<MigrationFeedbackResponse> getResponseList() {
    return responseList;
  }

  public void setResponseList(List<MigrationFeedbackResponse> responseList) {
    this.responseList = responseList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MigrationFeedbackResponseList migrationFeedbackResponseList = (MigrationFeedbackResponseList) o;
    return Objects.equals(this.responseList, migrationFeedbackResponseList.responseList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MigrationFeedbackResponseList {\n");
    
    sb.append("    responseList: ").append(toIndentedString(responseList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
