/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Neighbor properties
 */
@Schema(description = "Neighbor properties")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class NeighborProperties {
  @SerializedName("system_name")
  private String systemName = null;

  @SerializedName("system_desc")
  private String systemDesc = null;

  @SerializedName("system_port_number")
  private Long systemPortNumber = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("oid")
  private String oid = null;

  @SerializedName("mgmt_addr")
  private String mgmtAddr = null;

  @SerializedName("capabilities")
  private String capabilities = null;

  @SerializedName("link_aggregation_status")
  private Boolean linkAggregationStatus = null;

  @SerializedName("ifindex")
  private Long ifindex = null;

  @SerializedName("mac")
  private String mac = null;

  @SerializedName("link_aggregation_capable")
  private Boolean linkAggregationCapable = null;

  @SerializedName("port_desc")
  private String portDesc = null;

  @SerializedName("enabled_capabilities")
  private String enabledCapabilities = null;

  @SerializedName("link_aggregation_port_id")
  private String linkAggregationPortId = null;

   /**
   * System name
   * @return systemName
  **/
  @Schema(description = "System name")
  public String getSystemName() {
    return systemName;
  }

   /**
   * System description
   * @return systemDesc
  **/
  @Schema(description = "System description")
  public String getSystemDesc() {
    return systemDesc;
  }

   /**
   * System port number
   * @return systemPortNumber
  **/
  @Schema(description = "System port number")
  public Long getSystemPortNumber() {
    return systemPortNumber;
  }

   /**
   * Interface name
   * @return name
  **/
  @Schema(description = "Interface name")
  public String getName() {
    return name;
  }

   /**
   * Object identifier
   * @return oid
  **/
  @Schema(description = "Object identifier")
  public String getOid() {
    return oid;
  }

   /**
   * Management address
   * @return mgmtAddr
  **/
  @Schema(description = "Management address")
  public String getMgmtAddr() {
    return mgmtAddr;
  }

   /**
   * Capabilities
   * @return capabilities
  **/
  @Schema(description = "Capabilities")
  public String getCapabilities() {
    return capabilities;
  }

   /**
   * True if currently in aggregation
   * @return linkAggregationStatus
  **/
  @Schema(description = "True if currently in aggregation")
  public Boolean isLinkAggregationStatus() {
    return linkAggregationStatus;
  }

   /**
   * Interface index
   * @return ifindex
  **/
  @Schema(description = "Interface index")
  public Long getIfindex() {
    return ifindex;
  }

   /**
   * Interface MAC address
   * @return mac
  **/
  @Schema(description = "Interface MAC address")
  public String getMac() {
    return mac;
  }

   /**
   * Aggregation Capability
   * @return linkAggregationCapable
  **/
  @Schema(description = "Aggregation Capability")
  public Boolean isLinkAggregationCapable() {
    return linkAggregationCapable;
  }

   /**
   * Port description
   * @return portDesc
  **/
  @Schema(description = "Port description")
  public String getPortDesc() {
    return portDesc;
  }

   /**
   * Enabled capabilities
   * @return enabledCapabilities
  **/
  @Schema(description = "Enabled capabilities")
  public String getEnabledCapabilities() {
    return enabledCapabilities;
  }

   /**
   * Aggregation port id
   * @return linkAggregationPortId
  **/
  @Schema(description = "Aggregation port id")
  public String getLinkAggregationPortId() {
    return linkAggregationPortId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NeighborProperties neighborProperties = (NeighborProperties) o;
    return Objects.equals(this.systemName, neighborProperties.systemName) &&
        Objects.equals(this.systemDesc, neighborProperties.systemDesc) &&
        Objects.equals(this.systemPortNumber, neighborProperties.systemPortNumber) &&
        Objects.equals(this.name, neighborProperties.name) &&
        Objects.equals(this.oid, neighborProperties.oid) &&
        Objects.equals(this.mgmtAddr, neighborProperties.mgmtAddr) &&
        Objects.equals(this.capabilities, neighborProperties.capabilities) &&
        Objects.equals(this.linkAggregationStatus, neighborProperties.linkAggregationStatus) &&
        Objects.equals(this.ifindex, neighborProperties.ifindex) &&
        Objects.equals(this.mac, neighborProperties.mac) &&
        Objects.equals(this.linkAggregationCapable, neighborProperties.linkAggregationCapable) &&
        Objects.equals(this.portDesc, neighborProperties.portDesc) &&
        Objects.equals(this.enabledCapabilities, neighborProperties.enabledCapabilities) &&
        Objects.equals(this.linkAggregationPortId, neighborProperties.linkAggregationPortId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemName, systemDesc, systemPortNumber, name, oid, mgmtAddr, capabilities, linkAggregationStatus, ifindex, mac, linkAggregationCapable, portDesc, enabledCapabilities, linkAggregationPortId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NeighborProperties {\n");
    
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("    systemDesc: ").append(toIndentedString(systemDesc)).append("\n");
    sb.append("    systemPortNumber: ").append(toIndentedString(systemPortNumber)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    oid: ").append(toIndentedString(oid)).append("\n");
    sb.append("    mgmtAddr: ").append(toIndentedString(mgmtAddr)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    linkAggregationStatus: ").append(toIndentedString(linkAggregationStatus)).append("\n");
    sb.append("    ifindex: ").append(toIndentedString(ifindex)).append("\n");
    sb.append("    mac: ").append(toIndentedString(mac)).append("\n");
    sb.append("    linkAggregationCapable: ").append(toIndentedString(linkAggregationCapable)).append("\n");
    sb.append("    portDesc: ").append(toIndentedString(portDesc)).append("\n");
    sb.append("    enabledCapabilities: ").append(toIndentedString(enabledCapabilities)).append("\n");
    sb.append("    linkAggregationPortId: ").append(toIndentedString(linkAggregationPortId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
