/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NSGroupExpression;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Complex expressions to represent NSGroup membership
 */
@Schema(description = "Complex expressions to represent NSGroup membership")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class NSGroupComplexExpression extends NSGroupExpression {
  @SerializedName("expressions")
  private List<NSGroupExpression> expressions = new ArrayList<NSGroupExpression>();

  public NSGroupComplexExpression expressions(List<NSGroupExpression> expressions) {
    this.expressions = expressions;
    return this;
  }

  public NSGroupComplexExpression addExpressionsItem(NSGroupExpression expressionsItem) {
    this.expressions.add(expressionsItem);
    return this;
  }

   /**
   * Represents expressions which are to be logically &#x27;AND&#x27;ed.The array cannot contain NSGroupComplexExpression.Only NSGroupTagExpression and NSGroupSimpleExpressions are accepted. 
   * @return expressions
  **/
  @Schema(required = true, description = "Represents expressions which are to be logically 'AND'ed.The array cannot contain NSGroupComplexExpression.Only NSGroupTagExpression and NSGroupSimpleExpressions are accepted. ")
  public List<NSGroupExpression> getExpressions() {
    return expressions;
  }

  public void setExpressions(List<NSGroupExpression> expressions) {
    this.expressions = expressions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NSGroupComplexExpression nsGroupComplexExpression = (NSGroupComplexExpression) o;
    return Objects.equals(this.expressions, nsGroupComplexExpression.expressions) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expressions, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NSGroupComplexExpression {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    expressions: ").append(toIndentedString(expressions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
