/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Resource;
import io.swagger.client.model.ResourceLink;
import io.swagger.client.model.SelfResourceLink;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.List;
/**
 * PBRStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class PBRStats extends Resource {
  @SerializedName("packet_count")
  private Long packetCount = null;

  @SerializedName("byte_count")
  private Long byteCount = null;

  @SerializedName("rule_id")
  private String ruleId = null;

   /**
   * Aggregated number of packets processed by the rule.
   * @return packetCount
  **/
  @Schema(description = "Aggregated number of packets processed by the rule.")
  public Long getPacketCount() {
    return packetCount;
  }

   /**
   * Aggregated number of bytes processed by the rule.
   * @return byteCount
  **/
  @Schema(description = "Aggregated number of bytes processed by the rule.")
  public Long getByteCount() {
    return byteCount;
  }

   /**
   * Rule Identifier of the PBR rule. This is a globally unique number.
   * @return ruleId
  **/
  @Schema(description = "Rule Identifier of the PBR rule. This is a globally unique number.")
  public String getRuleId() {
    return ruleId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PBRStats pbRStats = (PBRStats) o;
    return Objects.equals(this.packetCount, pbRStats.packetCount) &&
        Objects.equals(this.byteCount, pbRStats.byteCount) &&
        Objects.equals(this.ruleId, pbRStats.ruleId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packetCount, byteCount, ruleId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PBRStats {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    packetCount: ").append(toIndentedString(packetCount)).append("\n");
    sb.append("    byteCount: ").append(toIndentedString(byteCount)).append("\n");
    sb.append("    ruleId: ").append(toIndentedString(ruleId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
