/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * A weak reference to an NSX resource.
 */
@Schema(description = "A weak reference to an NSX resource.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class ResourceReference {
  @SerializedName("target_display_name")
  private String targetDisplayName = null;

  @SerializedName("is_valid")
  private Boolean isValid = null;

  @SerializedName("target_id")
  private String targetId = null;

  @SerializedName("target_type")
  private String targetType = null;

   /**
   * Display name of the NSX resource.
   * @return targetDisplayName
  **/
  @Schema(description = "Display name of the NSX resource.")
  public String getTargetDisplayName() {
    return targetDisplayName;
  }

   /**
   * Will be set to false if the referenced NSX resource has been deleted.
   * @return isValid
  **/
  @Schema(description = "Will be set to false if the referenced NSX resource has been deleted.")
  public Boolean isIsValid() {
    return isValid;
  }

  public ResourceReference targetId(String targetId) {
    this.targetId = targetId;
    return this;
  }

   /**
   * Identifier of the NSX resource.
   * @return targetId
  **/
  @Schema(description = "Identifier of the NSX resource.")
  public String getTargetId() {
    return targetId;
  }

  public void setTargetId(String targetId) {
    this.targetId = targetId;
  }

  public ResourceReference targetType(String targetType) {
    this.targetType = targetType;
    return this;
  }

   /**
   * Type of the NSX resource.
   * @return targetType
  **/
  @Schema(description = "Type of the NSX resource.")
  public String getTargetType() {
    return targetType;
  }

  public void setTargetType(String targetType) {
    this.targetType = targetType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceReference resourceReference = (ResourceReference) o;
    return Objects.equals(this.targetDisplayName, resourceReference.targetDisplayName) &&
        Objects.equals(this.isValid, resourceReference.isValid) &&
        Objects.equals(this.targetId, resourceReference.targetId) &&
        Objects.equals(this.targetType, resourceReference.targetType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetDisplayName, isValid, targetId, targetType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceReference {\n");
    
    sb.append("    targetDisplayName: ").append(toIndentedString(targetDisplayName)).append("\n");
    sb.append("    isValid: ").append(toIndentedString(isValid)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    targetType: ").append(toIndentedString(targetType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
