/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.IpAssignmentSpec;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * IP assignment specification for Static IP Pool.
 */
@Schema(description = "IP assignment specification for Static IP Pool.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class StaticIpPoolSpec extends IpAssignmentSpec {
  @SerializedName("ip_pool_id")
  private String ipPoolId = null;

  public StaticIpPoolSpec ipPoolId(String ipPoolId) {
    this.ipPoolId = ipPoolId;
    return this;
  }

   /**
   * Get ipPoolId
   * @return ipPoolId
  **/
  @Schema(required = true, description = "")
  public String getIpPoolId() {
    return ipPoolId;
  }

  public void setIpPoolId(String ipPoolId) {
    this.ipPoolId = ipPoolId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaticIpPoolSpec staticIpPoolSpec = (StaticIpPoolSpec) o;
    return Objects.equals(this.ipPoolId, staticIpPoolSpec.ipPoolId) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ipPoolId, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaticIpPoolSpec {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    ipPoolId: ").append(toIndentedString(ipPoolId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
