/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ManagedResource;
import io.swagger.client.model.Tag;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.List;
/**
 * TrustObjectData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class TrustObjectData extends ManagedResource {
  @SerializedName("key_algo")
  private String keyAlgo = null;

  @SerializedName("private_key")
  private String privateKey = null;

  @SerializedName("passphrase")
  private String passphrase = null;

  @SerializedName("pem_encoded")
  private String pemEncoded = null;

  public TrustObjectData keyAlgo(String keyAlgo) {
    this.keyAlgo = keyAlgo;
    return this;
  }

   /**
   * Key algorithm contained in this certificate
   * @return keyAlgo
  **/
  @Schema(description = "Key algorithm contained in this certificate")
  public String getKeyAlgo() {
    return keyAlgo;
  }

  public void setKeyAlgo(String keyAlgo) {
    this.keyAlgo = keyAlgo;
  }

  public TrustObjectData privateKey(String privateKey) {
    this.privateKey = privateKey;
    return this;
  }

   /**
   * private key data
   * @return privateKey
  **/
  @Schema(description = "private key data")
  public String getPrivateKey() {
    return privateKey;
  }

  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }

  public TrustObjectData passphrase(String passphrase) {
    this.passphrase = passphrase;
    return this;
  }

   /**
   * Password for private key encryption
   * @return passphrase
  **/
  @Schema(description = "Password for private key encryption")
  public String getPassphrase() {
    return passphrase;
  }

  public void setPassphrase(String passphrase) {
    this.passphrase = passphrase;
  }

  public TrustObjectData pemEncoded(String pemEncoded) {
    this.pemEncoded = pemEncoded;
    return this;
  }

   /**
   * pem encoded certificate data
   * @return pemEncoded
  **/
  @Schema(required = true, description = "pem encoded certificate data")
  public String getPemEncoded() {
    return pemEncoded;
  }

  public void setPemEncoded(String pemEncoded) {
    this.pemEncoded = pemEncoded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrustObjectData trustObjectData = (TrustObjectData) o;
    return Objects.equals(this.keyAlgo, trustObjectData.keyAlgo) &&
        Objects.equals(this.privateKey, trustObjectData.privateKey) &&
        Objects.equals(this.passphrase, trustObjectData.passphrase) &&
        Objects.equals(this.pemEncoded, trustObjectData.pemEncoded) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keyAlgo, privateKey, passphrase, pemEncoded, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrustObjectData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    keyAlgo: ").append(toIndentedString(keyAlgo)).append("\n");
    sb.append("    privateKey: ").append(toIndentedString(privateKey)).append("\n");
    sb.append("    passphrase: ").append(toIndentedString(passphrase)).append("\n");
    sb.append("    pemEncoded: ").append(toIndentedString(pemEncoded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
