/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TrunkVlanRange;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * VlanTrunkspec is used for specifying trunk VLAN id ranges.
 */
@Schema(description = "VlanTrunkspec is used for specifying trunk VLAN id ranges.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class VlanTrunkSpec {
  @SerializedName("vlan_ranges")
  private List<TrunkVlanRange> vlanRanges = new ArrayList<TrunkVlanRange>();

  public VlanTrunkSpec vlanRanges(List<TrunkVlanRange> vlanRanges) {
    this.vlanRanges = vlanRanges;
    return this;
  }

  public VlanTrunkSpec addVlanRangesItem(TrunkVlanRange vlanRangesItem) {
    this.vlanRanges.add(vlanRangesItem);
    return this;
  }

   /**
   * Trunk VLAN id ranges
   * @return vlanRanges
  **/
  @Schema(required = true, description = "Trunk VLAN id ranges")
  public List<TrunkVlanRange> getVlanRanges() {
    return vlanRanges;
  }

  public void setVlanRanges(List<TrunkVlanRange> vlanRanges) {
    this.vlanRanges = vlanRanges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VlanTrunkSpec vlanTrunkSpec = (VlanTrunkSpec) o;
    return Objects.equals(this.vlanRanges, vlanTrunkSpec.vlanRanges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vlanRanges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VlanTrunkSpec {\n");
    
    sb.append("    vlanRanges: ").append(toIndentedString(vlanRanges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
