/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ManagedResource;
import io.swagger.client.model.Tag;
import io.swagger.client.model.VniRange;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * VniPool
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-19T07:44:41.574+08:00[Asia/Shanghai]")
public class VniPool extends ManagedResource {
  @SerializedName("ranges")
  private List<VniRange> ranges = new ArrayList<VniRange>();

  public VniPool ranges(List<VniRange> ranges) {
    this.ranges = ranges;
    return this;
  }

  public VniPool addRangesItem(VniRange rangesItem) {
    this.ranges.add(rangesItem);
    return this;
  }

   /**
   * VNI range list results
   * @return ranges
  **/
  @Schema(required = true, description = "VNI range list results")
  public List<VniRange> getRanges() {
    return ranges;
  }

  public void setRanges(List<VniRange> ranges) {
    this.ranges = ranges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VniPool vniPool = (VniPool) o;
    return Objects.equals(this.ranges, vniPool.ranges) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ranges, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VniPool {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
