/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ApiError;
import io.swagger.client.model.NormalizedResourceListResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManagementPlaneApiNormalizationApi
 */
@Ignore
public class ManagementPlaneApiNormalizationApiTest {

    private final ManagementPlaneApiNormalizationApi api = new ManagementPlaneApiNormalizationApi();

    /**
     * Get normalizations based on the query parameters
     *
     * Returns the list of normalized resources based on the query parameters. Id and Type of the resource on which the normalizations is to be performed, are to be specified as query parameters in the URI. The target resource types to which normalization is to be done should also be specified as query parameter. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNormalizationsTest() throws ApiException {
        String preferredNormalizationType = null;
        String resourceId = null;
        String resourceType = null;
        String cursor = null;
        String includedFields = null;
        Long pageSize = null;
        Boolean sortAscending = null;
        String sortBy = null;
        NormalizedResourceListResult response = api.getNormalizations(preferredNormalizationType, resourceId, resourceType, cursor, includedFields, pageSize, sortAscending, sortBy);

        // TODO: test validations
    }
}
