/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ApiError;
import io.swagger.client.model.LogicalConstructMigrationStatsListResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManagementPlaneApiMigrationStatsApi
 */
@Ignore
public class ManagementPlaneApiMigrationStatsApiTest {

    private final ManagementPlaneApiMigrationStatsApi api = new ManagementPlaneApiMigrationStatsApi();

    /**
     * Get migration stats for logical constructs phase
     *
     * Get migration stats for logical constructs phase. This API can be polled for getting runtime progress of the migration from source to target.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLogicalConstructMigrationStatsTest() throws ApiException {
        String cursor = null;
        String includedFields = null;
        Long pageSize = null;
        Boolean sortAscending = null;
        String sortBy = null;
        LogicalConstructMigrationStatsListResult response = api.getLogicalConstructMigrationStats(cursor, includedFields, pageSize, sortAscending, sortBy);

        // TODO: test validations
    }
}
