/*
 * NSX-T Manager API
 * VMware NSX-T Manager REST API
 *
 * OpenAPI spec version: 2.5.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ApiError;
import io.swagger.client.model.TransportNodeProfile;
import io.swagger.client.model.TransportNodeProfileListResult;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManagementPlaneApiNetworkTransportTransportNodeProfilesApi
 */
@Ignore
public class ManagementPlaneApiNetworkTransportTransportNodeProfilesApiTest {

    private final ManagementPlaneApiNetworkTransportTransportNodeProfilesApi api = new ManagementPlaneApiNetworkTransportTransportNodeProfilesApi();

    /**
     * Create a Transport Node Profile
     *
     * Transport node profile captures the configuration needed to create a transport node. A transport node profile can be attached to compute collections for automatic TN creation of member hosts. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTransportNodeProfileTest() throws ApiException {
        TransportNodeProfile body = null;
        TransportNodeProfile response = api.createTransportNodeProfile(body);

        // TODO: test validations
    }
    /**
     * Delete a Transport Node Profile
     *
     * Deletes the specified transport node profile. A transport node profile can be deleted only when it is not attached to any compute collection. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTransportNodeProfileTest() throws ApiException {
        String transportNodeProfileId = null;
        api.deleteTransportNodeProfile(transportNodeProfileId);

        // TODO: test validations
    }
    /**
     * Get a Transport Node
     *
     * Returns information about a specified transport node profile.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTransportNodeProfileTest() throws ApiException {
        String transportNodeProfileId = null;
        TransportNodeProfile response = api.getTransportNodeProfile(transportNodeProfileId);

        // TODO: test validations
    }
    /**
     * List Transport Nodes
     *
     * Returns information about all transport node profiles. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listTransportNodeProfilesTest() throws ApiException {
        String cursor = null;
        String includedFields = null;
        Long pageSize = null;
        Boolean sortAscending = null;
        String sortBy = null;
        TransportNodeProfileListResult response = api.listTransportNodeProfiles(cursor, includedFields, pageSize, sortAscending, sortBy);

        // TODO: test validations
    }
    /**
     * Update a Transport Node Profile
     *
     * When configurations of a transport node profile(TNP) is updated, all the transport nodes in all the compute collections to which this TNP is attached are updated to reflect the updated configuration. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTransportNodeProfileTest() throws ApiException {
        TransportNodeProfile body = null;
        String transportNodeProfileId = null;
        String esxMgmtIfMigrationDest = null;
        String ifId = null;
        String pingIp = null;
        String vnic = null;
        String vnicMigrationDest = null;
        TransportNodeProfile response = api.updateTransportNodeProfile(body, transportNodeProfileId, esxMgmtIfMigrationDest, ifId, pingIp, vnic, vnicMigrationDest);

        // TODO: test validations
    }
}
